color: null
fieldLayouts:
  655f017f-478e-4c06-af5b-cb8315913e41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42db2c81-2e82-4795-a590-e8212a622d34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8bf4141d-26ac-43e1-b06f-294b902f253b # Kleur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbce9641-3416-42a3-b7f7-86c1a719d77a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c12599d-8cf3-4ef8-b98a-2247d13c4066
        userCondition: null
handle: colors
hasTitleField: false
icon: ''
name: colors
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
