defaultPlacement: end
enableVersioning: true
entryTypes:
  - ffedbe34-2143-4ae9-9d32-94ec149cc47b
handle: cards
maxAuthors: 2
name: kaartjes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: kaartjes
structure:
  maxLevels: 1
  uid: d859b780-b880-410d-bfd5-eb539299dac2
type: structure
