defaultPlacement: end
enableVersioning: true
entryTypes:
  - bc312e20-887f-40c7-b503-7167836a9843 # colors
handle: colors
maxAuthors: 1
name: colors
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 62b1436d-d029-4061-a582-17706532cca5
type: structure
