defaultPlacement: end
enableVersioning: true
entryTypes:
  - 40e7b0e9-9f84-4223-afd8-7da568be1d75 # contact
handle: contact
maxAuthors: 2
name: contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: _contact.twig
    uriFormat: contact
type: single
