defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2f31dbb2-63f2-4126-a05b-cefeae14ad33 # homeTitle
handle: index
maxAuthors: 2
name: home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
