defaultPlacement: end
enableVersioning: true
entryTypes:
  - dc1e312b-9dde-4289-81f2-7c24afeb5f58 # products
handle: products
maxAuthors: 2
name: producten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: _detailPage.twig
    uriFormat: 'producten/{slug}'
structure:
  maxLevels: null
  uid: 42bf7715-c579-4bcd-b789-af667e802d39
type: structure
