defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1a10558c-3579-4dc8-8627-2bb1d7a7c173 # profile
handle: profile
maxAuthors: 2
name: profile
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: _profile.twig
    uriFormat: profile
type: single
