defaultPlacement: end
enableVersioning: true
entryTypes:
  - 185f4fd3-3f45-4507-b544-8c9316870cf9 # Sneakers Overzicht
handle: sneakersOverview
maxAuthors: 1
name: 'Sneaker Overzicht'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e067a129-ed5f-49b4-a717-848f79f1a5c4: # Positivitees
    enabledByDefault: true
    hasUrls: true
    template: _sneakers/_overview.twig
    uriFormat: our-sneakers
type: single
