altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  128dc819-8412-4f63-826f-a7a5f2fb5f32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ecc5c68b-611b-446e-9c1b-f62b85f2b2eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 309ad502-e6e1-4484-8953-f3a2f996ca18
        userCondition: null
fs: files
handle: files
name: bestanden
sortOrder: 1
subpath: files
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: files
transformSubpath: ''
