dateModified: 1715005540
email:
  fromEmail: 12001844@student.pxl.be
  fromName: Positivitees
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    aaf896d6-63eb-4bb4-a290-90337a31e01b: Positivitees # Positivitees
    e067a129-ed5f-49b4-a717-848f79f1a5c4: Positivitees # Positivitees
system:
  edition: solo
  live: true
  name: Positivitees
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
